<?php


$change_array = array("none" => 0, "read" => 1, "edit" => 2, "create" => 4, "upload" => 8, "delete" => 16, "admin" => 255);
$permissions_array = json_decode(file_get_contents("/rolesets.json"),true);


file_put_contents("/var/www/conf/acl.auth.php", "# acl.auth.php\n# <?php exit()?>\n# Don't modify the lines above\n#\n# Access Control Lists\n#\n# Auto-generated by install script\n# Date: Mon, 04 Jul 2016 10:51:54 +0000\n*               @ALL          0\n*               @user         8");

foreach($permissions_array as $key => $value) {
  $permissions_array[$key] = $change_array[$value];
  $identifier = strtolower(str_replace(":", "_", $key));
  file_put_contents("/var/www/conf/acl.auth.php", "\n*               @" . $key . "\t\t\t\t" . $permissions_array[$key], FILE_APPEND);
}
