<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user:
 * Date: Mon, 04 Jul 2016 12:52:37 +0200
 */

$conf['title'] = '{REPLACE_TITLE}';
$conf['license'] = '{REPLACE_LICENSE}';
$conf['useacl'] = 1;
$conf['authtype'] = 'oauth';
$conf['superuser'] = '@{REPLACE_SUPERUSER}';
$conf['plugin']['oauth']['dataporten-key'] = '{REPLACE_ID}';
$conf['plugin']['oauth']['dataporten-secret'] = '{REPLACE_SECRET}';

// end auto-generated content
